### ISSUE TITLE
Step fails on Export artifacts (zip) 

### ISSUE THREAD

**Issue by voxmaster** [bitrise-steplib/bitrise-step-flutter-build#13]
Step fails on Export artifacts (zip) with any output pattern set
Can I skip export?

With absolute path:
`/Users/vagrant/git/build/ios/iphoneos/Runner.app`

```
[ +714 ms] Built /Users/vagrant/git/build/ios/iphoneos/Runner.app.
[   +1 ms] "flutter ios" took 1,228,139ms.
Export iOS artifact
Failed to export iOS artifacts, error: command: (/usr/bin/zip "-rTy" "ios_build/Runner.app.zip" "Runner.app") failed, output: zip I/O error: No such file or directory
```

With default specifier
`*build/ios/iphoneos/*.app`

```
[ +623 ms] Built /Users/vagrant/git/build/ios/iphoneos/Runner.app.
[   +1 ms] "flutter ios" took 1,169,620ms.
Export iOS artifact
Failed to export iOS artifacts, error: command: (/usr/bin/zip "-rTy" "ios_build/Runner.app.zip" "Runner.app") failed, output: zip I/O error: No such file or directory
zip error: Could not create output file (ios_build/Runner.app.zip), error: exit status 15
```

With more specific path
`build/ios/iphoneos/*.app.`
```
Built /Users/vagrant/git/build/ios/iphoneos/Runner.app.
Export iOS artifact
panic: runtime error: index out of range
goroutine 1 [running]:
main.buildSpecification.exportIOSApp(0x131ffe2, 0x3, 0x131ffeb, 0x3, 0xc0000880a0, 0x2, 0x2, 0xc00007e2b0, 0x1, 0x1, ...)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit994526613/src/github.com/bitrise-steplib/bitrise-step-flutter-build/buildspec.go:58 +0x407
main.buildSpecification.exportArtifacts(0x131ffe2, 0x3, 0x131ffeb, 0x3, 0xc0000880a0, 0x2, 0x2, 0xc00007e2b0, 0x1, 0x1, ...)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit994526613/src/github.com/bitrise-steplib/bitrise-step-flutter-build/buildspec.go:39 +0x2ac
main.main()
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit994526613/src/github.com/bitrise-steplib/bitrise-step-flutter-build/main.go:213 +0x104e
```

**Comment by bitce** [comment]
Hi @voxmaster!

Sorry for the delay and thanks for your report! Can you please include builds URLs of these instances so we can look into them in more detail?

**Comment by DamienBitrise** [comment]
This is caused when you try to export iphoneos artifacts but only build iphonesimulator artifacts

Index out of bounds here when artifacts length is 0 (We should check the artifacts length here)

https://github.com/bitrise-steplib/bitrise-step-flutter-build/blob/master/buildspec.go#L58

You should be able to fix this issue by changing your Flutter Build steps Output Pattern setting to:

*build/ios/iphonesimulator/*.app

**Comment by voxmaster** [comment]
Thanks for your replies, but it's been a long time ago. So I'm not able to check any of methods above.
