### ISSUE TITLE
Invalid argument(s) #0 _StringBase._interpolate (dart:core-patch/string_patch.dart:854:9)

### ISSUE THREAD

**Issue by kndl22** [bitrise-steplib/bitrise-step-flutter-build#26]
Hi,
The flutter build fails with the following error:

```
Invalid argument(s)
#0      _StringBase._interpolate (dart:core-patch/string_patch.dart:854:9)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:92:70)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _runZoned (dart:async/zone.dart:1630:10)
#19     runZoned (dart:async/zone.dart:1550:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:282:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:223:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:69:22)
#27     _rootRun (dart:async/zone.dart:1190:13)
#28     _CustomZone.run (dart:async/zone.dart:1093:19)
#29     _runZoned (dart:async/zone.dart:1630:10)
#30     runZonedGuarded (dart:async/zone.dart:1618:12)
#31     runZoned (dart:async/zone.dart:1547:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:67:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:62:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1190:13)
#38     _CustomZone.run (dart:async/zone.dart:1093:19)
#39     _runZoned (dart:async/zone.dart:1630:10)
#40     runZoned (dart:async/zone.dart:1550:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#43     run (package:flutter_tools/runner.dart:52:10)
#44     main (package:flutter_tools/executable.dart:73:9)
#45     main (file:///Users/vagrant/flutter-sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Failed to build iOS platform, error: exit status 1
```

The failure started lately and I assume it's because of the new Flutter version 1.20, but I can't tell exactly why.

After a quick search seems that it has something with the flavours naming as mentioned in the flutter [git issues]:
(https://github.com/flutter/flutter/issues/59029)

Any way to overcome the issue without changing the flavours names, as it affects other app settings?

**Comment by non-binary** [comment]
Hi @kndl22,

I recommend sharing this on the forum! https://discuss.bitrise.io/

**Comment by kndl22** [comment]
Hi @non-binary , will do :)

**Comment by gau187** [comment]
@kndl22 did you get any solution i am also facing the same issue

**Comment by kndl22** [comment]
Yea,
Flutter team did a cherrypick regarding this issue,
Using the latest stable version should work for you.

The error usually comes from iOS scheme naming, when using lower case names - more info here: https://github.com/flutter/flutter/pull/63591
